name: id3tag
description: A cross-platform, pure-Dart package for reading ID3 meta data
version: 0.1.0
homepage: https://github.com/tolo/id3tag

environment:
  sdk: ">=2.13.0 <3.0.0"

dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.21.4
